[package]
name = "market_data"
version = "0.1.0"
authors = ["rkrasiuk <rokrassyuk@gmail.com>"]

[dependencies]
reqwest = "0.9.5"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
tungstenite = "0.6.1"
url = "1.7.2"
futures = "0.1.25"
futures-backoff = "0.1"
failure = "0.1.3"